apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=       # Base64 encoded string for "username"
  mongo-root-password: cGFzc3dvcmQ= # Base64 encoded string for "password"
